apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: database-glpi
  name: database-glpi
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: database-glpi
    spec:
      containers:
      - args:
        - mysqld
        - --sql_mode=
        env:
        - name: MYSQL_DATABASE
          value: glpi
        - name: MYSQL_PASSWORD
          value: "12345678"
        - name: MYSQL_ROOT_PASSWORD
          value: "12345678"
        - name: MYSQL_USER
          value: usr_aplicacao
        image: mysql:5.7
        name: database-mysql-glpi
        ports:
        - containerPort: 3306
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/mysql
          subPath: pasta-mysql-glpi
          name: database-glpi-claim0
      restartPolicy: Always
      volumes:
      - name: database-glpi-claim0
        persistentVolumeClaim:
          claimName: nfsserver-vm-generic-pvc
status: {}
