apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: web-glpi
  name: web-glpi
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: web-glpi
    spec:
      containers:
      - env:
        - name: APPLICATION_ENV
          value: development
        image: alyssontkd/ambiente-glpi
        name: glpiv10
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /var/www/html/dev.glpi.com.br
          subPath: pasta-glpi-web
          name: web-glpi-claim0
      restartPolicy: Always
      volumes:
      - name: web-glpi-claim0
        persistentVolumeClaim:
          claimName: nfsserver-vm-generic-pvc
status: {}
