version: '2'
services:
  database:
   build: .
   image: alyssontkd/mysql:5.7
   container_name: 'database-mysql'
   expose:
        - "3306"
   ports:
        - "3306:3306"
   volumes:
        - /var/www/database/mysql/conf.d:/etc/mysql/conf.d
        - /var/www/database/mysql/mysql.conf.d:/etc/mysql/mysql.conf.d
        - /var/www/database/mysql/data:/var/lib/mysql
        - /var/www/database/mysql/log:/var/log/
   environment:
        MYSQL_ROOT_PASSWORD: 12345678
        MYSQL_USER: usr_aplicacao
        MYSQL_PASSWORD: 12345678
        #MYSQL_DATABASE: bdplanomudanca
