FROM mysql:5.7


RUN apt-get update

#vim is usefull for debug container in interactive shell
RUN apt-get install -y vim
RUN apt-get install -y telnet

#Expoe a porta 3306 para ficar acessivel do HOST
EXPOSE 3306
